title: Minimal theme
logo: /assets/img/logo.png
description: Minimal is a theme for GitHub Pages.
show_downloads: true
google_analytics:

# Navigation menu (tabs)
nav_links:
  - name: "Home"
    url: "/"
  - name: "About"
    url: "/about"
  - name: "Blog"
    url: "/blog"
  - name: "Contact"
    url: "/contact"
